name: ${project.name}
version: ${project.version}
main: ${project.groupId}.${project.artifactId}
api-version: 1.13
authors: [Gimme]
description: ${project.description}
softdepend: [GimmeCore, ProtocolLib, EssentialsXSpawn, Vault]

commands:
  logout:
    description: Safely log out
    permission: gimmebalance.logout

permissions:
  gimmebalance.logout:
    description: Allows using the logout command
    default: true
